/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReciteRouteImport } from './routes/recite'
import { Route as HalaqatInterestRouteImport } from './routes/halaqat-interest'
import { Route as IndexRouteImport } from './routes/index'

const ReciteRoute = ReciteRouteImport.update({
  id: '/recite',
  path: '/recite',
  getParentRoute: () => rootRouteImport,
} as any)
const HalaqatInterestRoute = HalaqatInterestRouteImport.update({
  id: '/halaqat-interest',
  path: '/halaqat-interest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/halaqat-interest': typeof HalaqatInterestRoute
  '/recite': typeof ReciteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/halaqat-interest': typeof HalaqatInterestRoute
  '/recite': typeof ReciteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/halaqat-interest': typeof HalaqatInterestRoute
  '/recite': typeof ReciteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/halaqat-interest' | '/recite'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/halaqat-interest' | '/recite'
  id: '__root__' | '/' | '/halaqat-interest' | '/recite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HalaqatInterestRoute: typeof HalaqatInterestRoute
  ReciteRoute: typeof ReciteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recite': {
      id: '/recite'
      path: '/recite'
      fullPath: '/recite'
      preLoaderRoute: typeof ReciteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halaqat-interest': {
      id: '/halaqat-interest'
      path: '/halaqat-interest'
      fullPath: '/halaqat-interest'
      preLoaderRoute: typeof HalaqatInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HalaqatInterestRoute: HalaqatInterestRoute,
  ReciteRoute: ReciteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
