/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HalaqatInterestRouteImport } from './routes/halaqat-interest'
import { Route as IndexRouteImport } from './routes/index'

const HalaqatInterestRoute = HalaqatInterestRouteImport.update({
  id: '/halaqat-interest',
  path: '/halaqat-interest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/halaqat-interest': typeof HalaqatInterestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/halaqat-interest': typeof HalaqatInterestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/halaqat-interest': typeof HalaqatInterestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/halaqat-interest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/halaqat-interest'
  id: '__root__' | '/' | '/halaqat-interest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HalaqatInterestRoute: typeof HalaqatInterestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/halaqat-interest': {
      id: '/halaqat-interest'
      path: '/halaqat-interest'
      fullPath: '/halaqat-interest'
      preLoaderRoute: typeof HalaqatInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HalaqatInterestRoute: HalaqatInterestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
